### ISSUE TITLE
Errors parsing XML files containing user names with special characters

### ISSUE THREAD

**Issue by tordanik** [topobyte/osm4j#11]
OSM2World users have encountered problems when working with OSM XML files containing user names with certain characters – see [OSM2World issue #205](https://github.com/tordanik/OSM2World/issues/205) for context. These errors appear to originate from osm4j 1.2.0.

The example mentioned is user ["osm-pt-account 😎"](https://www.openstreetmap.org/user/osm-pt-account%20%f0%9f%98%8e). I've created a [fictional example XML file](https://github.com/topobyte/osm4j/files/10716087/username_emoji.zip) for easier reproduction. (Zipped to work around GitHub's allowed file types.)

**Comment by sebkur** [comment]
Thanks for your report, I'll look into it.

**Comment by sebkur** [comment]
I just added a test here https://github.com/topobyte/osm4j/commit/88db07393e9d17045902c5bc862806d0fe24e757

and cannot produce a problem with it.

I originally tried with the exact file you uploaded but modified it now a bit to remove the original username and changeset id. The original file has also been parsed fine.

**Comment by tordanik** [comment]
As it turns out, this was caused by the way OSM2World handles XML files created by JOSM. I believe this issue can be closed, and I'm sorry for jumping to the conclusion that this was an osm4j issue.

**Comment by sebkur** [comment]
Never mind, thanks for reaching out.
